### PR TITLE
feat: Dismiss Job Cancelled in SD

### PR DESCRIPTION
**Pull request by dokimyj**
## Context

For now, a single job in the Jenkins queue is not dismissed although the job has actually been cancelled in screwdriver-cd. 
This attribute induces accumulation of the Jenkins queue, especially for the pipelines which have many jobs defined.

## Objective

Jobs cancelled in the screwdriver-cd interface would also be deleted from the queue list of the Jenkins.

## References

N/A

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Review by jithine — CHANGES_REQUESTED** [review]
Thank you for this Pull Request. But can you update PR description as per our Template - https://github.com/screwdriver-cd/.github/blob/master/PULL_REQUEST_TEMPLATE.md

**Comment by dokimyj** [comment]
Fixed my PR in accordance with the template.

**Review by tkyi — APPROVED** [review]

**Comment by dokimyj** [comment]
@jithine @tkyi I squashed comments because there had been too many commit messages out of format set in this repository. Would you please check this PR again if good to go? Thank you.

**Review by tkyi — APPROVED** [review]

**Pull request merged**
